### PR TITLE
#267 - Add API Connector to Pull Audit Logs from Torq

### PR DESCRIPTION
**Pull request by kostyay**
This resolves issue https://github.com/IBM/IBM-QRadar-Universal-Cloud-REST-API/issues/267

### CODE REVIEW

**Review by ChrisCollinsIBM — CHANGES_REQUESTED** [review]
Overall the workflow looks great, well-formed, handled paging, awesome!

The one Item I'd like to see updated is to use the latest schema V2_1 which allows the omission of the `source` attribute on postEvents. 

Although things look like they will work now so long as the user configures the correct log source identifier, the new method we implemented to allow the identifier to be whatever the user wants is much cleaner and less error prone.

Let me know if you want to make this update or prefer to submit as-is.

**Comment by kostyay** [comment]
Hi
Please see the changes.
Not sure why DCO fails..

**Comment by kostyay** [comment]
@ChrisCollinsIBM any chance to get this marged?
Thanks

**Comment by ChrisCollinsIBM** [comment]
Looks good, the pre-squash makes it harder to see the changes between the review and the update but since the changes were small it's easy to check.

Thanks again for the submissions! Hopefully the new 2.1 schema with the optional `source` tag makes it easier for users of the workflow.

**Review by ChrisCollinsIBM — APPROVED** [review]

**Pull request merged**
