### PR TITLE
git commit -m "addition-of-audit-logs-workflow" #221

### PR DESCRIPTION
**Pull request by suraj-metron**

### CODE REVIEW

**Review by ChrisCollinsIBM — COMMENTED** [review]
Can you explain when someone would use `Wiz-AuditLogs-Workflow.xml` vs `Wiz-Workflow.xml` ? 

I see that the gql_query was added to `Wiz-Workflow.xml` but it's the same query referenced in both.

If one is just leftover it should be removed, and if they are for different things then can you update the README.md so people know what to use them for?

**Review by ChrisCollinsIBM — CHANGES_REQUESTED** [review]
Can you explain when someone would use `Wiz-AuditLogs-Workflow.xml` vs `Wiz-Workflow.xml` ?

I see that the gql_query was added to `Wiz-Workflow.xml` but it's the same query referenced in both.

If one is just leftover it should be removed, and if they are for different things then can you update the README.md so people know what to use them for?

It looks like `Wiz-Workflow.xml` might be for events vs audit logs so explaining that in the README.md would help the user.

**Comment by suraj-metron** [comment]
> Can you explain when someone would use `Wiz-AuditLogs-Workflow.xml` vs `Wiz-Workflow.xml` ?
> 
> I see that the gql_query was added to `Wiz-Workflow.xml` but it's the same query referenced in both.
> 
> If one is just leftover it should be removed, and if they are for different things then can you update the README.md so people know what to use them for?
> 
> It looks like `Wiz-Workflow.xml` might be for events vs audit logs so explaining that in the README.md would help the user.

Hi @ChrisCollinsIBM 

We have Wiz-Workflow to fetch Wiz Issues whereas Wiz-AuditLogs_Workflow to pull Wiz Audit Logs.
As per your suggestion we have updated the ReadMe file to update the same

**Comment by suraj-metron** [comment]
Hi @ChrisCollinsIBM 
Can you please review the PR and let us know if any actions are required from our side?
Thanks

**Review by ChrisCollinsIBM — APPROVED** [review]

**Pull request merged**
